# Generated by Django 6.0.4 on 2026-05-29 05:50

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.update(
        is_email_verified=True,
        email_verification_code='',
        email_verification_sent_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
