# Generated by Django 6.0.4 on 2026-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_package_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
