from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    AboutView,
    AdminPanelView,
    BlogView,
    CartAddItemView,
    CartClearView,
    CartDataView,
    CartRemoveItemView,
    CheckoutAddressView,
    CheckoutPayView,
    DashboardAddressSaveView,
    DashboardDataView,
    DashboardPasswordChangeView,
    DashboardProfileUpdateView,
    BookingView,
    CartView,
    CustomLoginView,
    DashboardView,
    HomeView,
    PackagesView,
    ServicesView,
    SignUpView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServicesView.as_view(), name='services'),
    path('packages/', PackagesView.as_view(), name='packages'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/data/', CartDataView.as_view(), name='cart_data'),
    path('cart/add/', CartAddItemView.as_view(), name='cart_add'),
    path('cart/remove/', CartRemoveItemView.as_view(), name='cart_remove'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('checkout/address/', CheckoutAddressView.as_view(), name='checkout_address'),
    path('checkout/pay/', CheckoutPayView.as_view(), name='checkout_pay'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/data/', DashboardDataView.as_view(), name='dashboard_data'),
    path('dashboard/profile/', DashboardProfileUpdateView.as_view(), name='dashboard_profile_update'),
    path('dashboard/address/save/', DashboardAddressSaveView.as_view(), name='dashboard_address_save'),
    path('dashboard/password/change/', DashboardPasswordChangeView.as_view(), name='dashboard_password_change'),
    path('admin-panel/', AdminPanelView.as_view(), name='admin_panel'),
    # Legacy .html URLs (compatibility while frontend transitions to Django URLs)
    path('index.html', HomeView.as_view(), name='home_html'),
    path('about.html', AboutView.as_view(), name='about_html'),
    path('services.html', ServicesView.as_view(), name='services_html'),
    path('packages.html', PackagesView.as_view(), name='packages_html'),
    path('booking.html', BookingView.as_view(), name='booking_html'),
    path('cart.html', CartView.as_view(), name='cart_html'),
    path('blog.html', BlogView.as_view(), name='blog_html'),
    path('user-dashboard.html', DashboardView.as_view(), name='dashboard_html'),
]
