from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from .views import (
    AboutView,
    AdminPanelView,
    BettyVersePasswordResetView,
    BlogView,
    CartAddItemView,
    CartClearView,
    CartDataView,
    CartRemoveItemView,
    CheckoutAddressView,
    CheckoutPayView,
    CheckoutStripeSessionView,
    CheckoutStripeWebhookView,
    DashboardAddressSaveView,
    DashboardDataView,
    DashboardPasswordChangeView,
    DashboardProfileUpdateView,
    NewsletterAdminView,
    NewsletterSubscribeView,
    NewsletterSubscribeSuccessView,
    NewsletterSubscriberToggleView,
    BookingView,
    CartView,
    CustomLoginView,
    DashboardView,
    HomeView,
    PackageDetailView,
    PackagesView,
    ServicesView,
    SignUpView,
    VerifyEmailView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServicesView.as_view(), name='services'),
    path('package-detail/', PackageDetailView.as_view(), name='package_detail'),
    path('packages/', PackagesView.as_view(), name='packages'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/data/', CartDataView.as_view(), name='cart_data'),
    path('cart/add/', CartAddItemView.as_view(), name='cart_add'),
    path('cart/remove/', CartRemoveItemView.as_view(), name='cart_remove'),
    path('cart/clear/', CartClearView.as_view(), name='cart_clear'),
    path('checkout/address/', CheckoutAddressView.as_view(), name='checkout_address'),
    path('checkout/pay/', CheckoutPayView.as_view(), name='checkout_pay'),
    path('checkout/stripe/session/', CheckoutStripeSessionView.as_view(), name='checkout_stripe_session'),
    path('checkout/stripe/webhook/', CheckoutStripeWebhookView.as_view(), name='checkout_stripe_webhook'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('newsletter/subscribe/', NewsletterSubscribeView.as_view(), name='newsletter_subscribe'),
    path('newsletter/success/', NewsletterSubscribeSuccessView.as_view(), name='newsletter_subscribe_success'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify_email'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path(
        'password-reset/',
        BettyVersePasswordResetView.as_view(
            template_name='login/password_reset.html',
            email_template_name='login/password_reset_email.txt',
            subject_template_name='login/password_reset_subject.txt',
            success_url=reverse_lazy('password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='login/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='login/password_reset_confirm.html',
            success_url=reverse_lazy('password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='login/password_reset_complete.html'),
        name='password_reset_complete',
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/data/', DashboardDataView.as_view(), name='dashboard_data'),
    path('dashboard/profile/', DashboardProfileUpdateView.as_view(), name='dashboard_profile_update'),
    path('dashboard/address/save/', DashboardAddressSaveView.as_view(), name='dashboard_address_save'),
    path('dashboard/password/change/', DashboardPasswordChangeView.as_view(), name='dashboard_password_change'),
    path('admin-panel/', AdminPanelView.as_view(), name='admin_panel'),
    path('admin-panel/newsletters/', NewsletterAdminView.as_view(), name='newsletter_admin'),
    path('admin-panel/newsletters/subscribers/<int:subscriber_id>/toggle/', NewsletterSubscriberToggleView.as_view(), name='newsletter_subscriber_toggle'),
    # Legacy .html URLs (compatibility while frontend transitions to Django URLs)
    path('index.html', HomeView.as_view(), name='home_html'),
    path('about.html', AboutView.as_view(), name='about_html'),
    path('services.html', ServicesView.as_view(), name='services_html'),
    path('packages.html', PackagesView.as_view(), name='packages_html'),
    path('packages/packages.html', PackagesView.as_view(), name='packages_nested_html'),
    path('booking.html', BookingView.as_view(), name='booking_html'),
    path('cart.html', CartView.as_view(), name='cart_html'),
    path('blog.html', BlogView.as_view(), name='blog_html'),
    path('user-dashboard.html', DashboardView.as_view(), name='dashboard_html'),
]
